version: "1"
services:
  postgres:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
  keycloak:
      image: quay.io/keycloak/keycloak:21.0.2
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin123
        KEYCLOAK_LOGLEVEL: INFO
        ROOT_LOGLEVEL: INFO
      ports:
        - 8080:8080
      command:
        - start-dev
      depends_on:
        - postgres
      volumes:
        - keycloak_data:/opt/jboss/keycloak/standalone/data/

volumes:
  keycloak_data:
  postgres_data:
