spring:
  application:
    name: occupancyapp
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8069/realms/OCCUPANCY
          jwk-set-uri: http://localhost:8069/realms/OCCUPANCY/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: occupancyclient
      principal-attribute: preferred_username

logging:
  level:
    org.springframework.security: DEBUG

server:
  port: '18069'
  servlet:
    context-path: /api








