version: "1"
services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: 123
    ports:
      - 5432:5432
  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: 123
      KEYCLOAK_LOGLEVEL: INFO
      ROOT_LOGLEVEL: INFO
    ports:
      - 8069:8080
    command:
      - start-dev
    depends_on:
      - postgres
    volumes:
      - ./Keycloak_Config:/opt/keycloak/Keycloak_Config

  spring:
    image: springtest:1.0
    environment:
      - spring_security_oauth2_resourceserver_jwt_issuer-uri=http://keycloak:8080/realms/OCCUPANCY
      - spring_security_oauth2_client_provider_keycloak_issuer-uri=http://keycloak:8080/realms/OCCUPANCY
      - spring_security_oauth2_resourceserver_jwt_jwk-set-uri=http://keycloak:8080/realms/OCCUPANCY/protocol/openid-connect/certs
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - spring_security_oauth2_client_registration_keycloak_client-secret=oINKNcsDqmO78Qb5aIiJcbI6kHpgy5Y4

    depends_on:
      - keycloak
    ports:
      - 18069:18069

  nginx:
    image: nginx:latest
    ports:
      - 999:999



volumes:
  Keycloak_Config:
  postgres_data:
